Models/Task.cs
using System;

namespace MyProject.Models
{
    public class Task
    {
        public int Id { get; set; }
        public string UserId { get; set; }
        public string TaskName { get; set; }
        public string Description { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime CompletedAt { get; set; }
        public bool Status { get; set; }
        public bool isAssigned { get; set; }
        public bool isCompleted{get; set;}
    }
}

Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MyProject.Data;
using MyProject.GenericRepository;
using MyProject.Models;
using MyProject.Repository;
using MyProject.ViewModel;

namespace TaskProject.Controllers
{
    [Authorize]
    public class TaskController : Controller
    {
       
        private readonly ITaskRepository _task;
        private readonly UserManager<IdentityUser> _userManager;

        public TaskController(ITaskRepository task,UserManager<IdentityUser>  userManager)
        {
           
            _task = task;
            _userManager = userManager;
        }
        public IActionResult Index()
        {
            
            var currentUser = _userManager.GetUserId(HttpContext.User);
            var tasks = _task.getUnAssignedTask().Where(x=>x.UserId== currentUser).ToList();;
            return View(tasks);
        }
        public IActionResult Create()
        {
            ViewBag.Message = "New";
            return View();
        }
        [HttpPost]
        public IActionResult Create(Task t,string message)
        {
            var currentUser = _userManager.GetUserId(HttpContext.User);
            t.UserId = currentUser;
            if(message.Equals("Update"))
            {
                _task.Update(t);
                
            }
            else if(message.Equals("New")){
            _task.Insert(t);
            }
            _task.Commit();
            return RedirectToAction("Index");
        }
        public IActionResult Assigned()
        {
            
           var data = _task.GetBy(x=>x.isAssigned==true).ToList();
            return View(data);
        }
      
        public IActionResult Assign(int id)
        {
            
            var assignTask = _task.GetSingle(x=>x.Id== id);
            assignTask.isAssigned = true;
            _task.Update(assignTask);
            _task.Commit(); 
            return RedirectToAction("Assigned");
            
        }

        public IActionResult Completed(int id)
        {
            var completeTask = _task.GetSingle(x=>x.Id== id);
            completeTask.isCompleted = true;
            completeTask.CompletedAt = DateTime.Now;
            _task.Update(completeTask);
            _task.Commit();

            return RedirectToAction("Assigned");
        }

        public IActionResult Update(int id)
        {
            ViewBag.Message= "Update";
            var data = _task.GetSingle(x=>x.Id == id);
            return View(nameof(Create),data);

        }

        public IActionResult Delete(int id)
        {
            _task.Delete(x=>x.Id== id);
            _task.Commit();
          
            return RedirectToAction("Index");
           
        }
    }
}

Views/Task/Assigned.cshtml
@model List<MyProject.Models.Task>
<input type="hidden" value ="@ViewBag.Message" name="message" id="message"class="form-control" />
<table class="table">
  <thead>
    <tr>
      
      <th scope="col">Task Name</th>
      <th scope="col">Description</th>
      <th scope="col">Created At</th>
      <th scope="col">Status</th>

    </tr>
  </thead>
  <tbody>
     
    @foreach (var item in Model)
    {
       
              <tr>
      <td>@item.TaskName</td>
      <td>@item.Description</td>
      <td>@item.CreatedAt</td>
      @if (@item.isCompleted==false)
      {
          <td> Not Completed</td>
        <td><a class="btn btn-primary" asp-controller="Task" asp-action="Completed" asp-route-id="@item.Id">Done</a></td>

      }else{
          <td> Completed At @item.CompletedAt.ToShortDateString()</td>
        }
         <td><a class="btn btn-danger delete" asp-controller="Task" asp-action="Delete" asp-route-id="@item.Id" data-body-message="Are You Sure Want To Delete ">Delete</a></td>


      </tr>
        }
      
    
    
  
  </tbody>
</table>

Views/Task/Create.cshtml
@model MyProject.Models.Task
<form method="post" asp-action="Create" asp-controller="Task">
  <div class="form-group">
    
    <input type="hidden" value ="@ViewBag.Message" name="message" id="message"class="form-control" />
    <input type="hidden" asp-for="Id"/>
  </div>
  <div class="form-group">
    <label asp-for="TaskName">Task Name</label>
    <input asp-for="TaskName" type="text" class="form-control" placeholder="Enter Task Name">
   
  </div>
  <div class="form-group">
    <label asp-for="Description">Description</label>
    <input asp-for="Description" type="text" class="form-control"  placeholder="Task Description">
  </div>
  
  <button type="submit" class="btn btn-primary">Submit</button>
</form>

Views/Task/Index.cshtml
@model List<MyProject.ViewModel.TaskIndexView>
<input type="hidden" value ="@ViewBag.Message" name="message" id="message"class="form-control" />
<table class="table">
  <thead>
    <tr>
      
      <th scope="col">Task Name</th>
      <th scope="col">Description</th>
      <th scope="col">Created At</th>
      <th scope="col">Action</th>

    </tr>
  </thead>
  <tbody>
     
    @foreach (var item in Model)
    {
       
              <tr>
      <td>@item.TaskName</td>
      <td>@item.Description</td>
      <td>@item.CreatedAt</td>
  
        <td><a class="btn btn-primary" asp-controller="Task" asp-action="Assign" asp-route-id="@item.TaskId">Assign</a></td>
        <td><a class="btn btn-primary" asp-controller="Task" asp-action="Update"  asp-route-id="@item.TaskId">Update</a></td>
        <td><a class="btn btn-danger delete" asp-controller="Task" asp-action="Delete" asp-route-id="@item.TaskId" data-body-message="Are You Sure Want To Delete ">Delete</a></td>


      </tr>
        
      
    }
    
     
    
  
  </tbody>
</table>